# Favicon
favicon: 'theme-doku/img/favicon.ico'

# --------------------
# Navbar
# --------------------
navbar:
  # The URL of Logo which will be shown at navbar
  logo: 'theme-doku/img/logo.png'
  # If you Logo has no text, you can add title next to your logo.
  # Leave it as an empty string if you don't have
  logo_text: 'Doku'
  links:
    - logo: # The font-awesome class name of the logo. Leave it blank if you don't need logo for this link
      text: '使用文档' # The logo text
      url: '/' # The url
    - logo: 'fab fa-github' # The font-awesome class name of the logo
      text: '' # The logo text
      url: 'https://github.com/SukkaW/hexo-theme-doku' # The url
